config:
  security:
    oauth:
      client:
        id: client-react-app
        secret: 12345
      jwt:
        key: $Ecr3t-1d3e31212ds-AzF-$$$pe-1wwe2e4r

spring:
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    host: microservicios-rabbitmq38