spring:
  datasource:  
    url: jdbc:mysql://localhost:3306/db_springboot_cloud?serverTimezome=America/Lima
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      
logging:
  level:
    org:
      hibernate:
        SQL: debug